import { useMemo, useState } from "react";
import { gamePlans, priorityList, firstProject, type GamePlan } from "./data/plans";

function MilestoneTable({ plan }: { plan: GamePlan }) {
  return (
    <div className="milestones">
      {plan.workPlan.map((m) => (
        <div className="milestone" key={m.name}>
          <div className="milestone-head">
            <span className="milestone-name">{m.name}</span>
            <span className="milestone-duration">{m.duration}</span>
          </div>
          {m.dependencies && <div className="milestone-dep">↳ depends on: {m.dependencies}</div>}
          <ul className="milestone-tasks">
            {m.tasks.map((t) => (
              <li key={t}>{t}</li>
            ))}
          </ul>
        </div>
      ))}
    </div>
  );
}

function PlanCard({ plan }: { plan: GamePlan }) {
  const [open, setOpen] = useState(false);
  return (
    <article className="card">
      <button className="card-head" onClick={() => setOpen((o) => !o)}>
        <span className="card-title">{plan.title}</span>
        <span className="card-genre">{plan.genre}</span>
        <span className="card-toggle">{open ? "−" : "+"}</span>
      </button>
      <p className="card-core">{plan.coreGameplay}</p>
      <div className="card-meta">
        <div>
          <h4>Target audience</h4>
          <p>{plan.audience}</p>
        </div>
        <div>
          <h4>Monetization</h4>
          <p>{plan.monetization}</p>
        </div>
      </div>
      <div className="card-features">
        <h4>Main features</h4>
        <ul>
          {plan.features.map((f) => (
            <li key={f}>{f}</li>
          ))}
        </ul>
      </div>
      {open && (
        <div className="card-plan">
          <h4>Work plan</h4>
          <MilestoneTable plan={plan} />
        </div>
      )}
    </article>
  );
}

export default function App() {
  const [query, setQuery] = useState("");
  const filtered = useMemo(() => {
    const q = query.trim().toLowerCase();
    if (!q) return gamePlans;
    return gamePlans.filter(
      (p) =>
        p.title.toLowerCase().includes(q) ||
        p.genre.toLowerCase().includes(q) ||
        p.coreGameplay.toLowerCase().includes(q)
    );
  }, [query]);

  return (
    <div className="shell">
      <header className="header">
        <div className="header-inner">
          <div>
            <h1>Mobile Game Work Plans</h1>
            <p className="subtitle">
              Planning-only work plans for 15 mobile game concepts · MaximoSEO
            </p>
          </div>
          <input
            className="search"
            placeholder="Search ideas…"
            value={query}
            onChange={(e) => setQuery(e.target.value)}
          />
        </div>
      </header>

      <main className="main">
        <section className="section">
          <h2>Priority Development List</h2>
          <ol className="priority">
            {priorityList.map((p) => (
              <li key={p.rank} className="priority-item">
                <span className="priority-rank">{p.rank}</span>
                <div>
                  <strong>{p.title}</strong>
                  <p>{p.why}</p>
                </div>
              </li>
            ))}
          </ol>
        </section>

        <section className="section first">
          <h2>Recommended First Project</h2>
          <div className="first-card">
            <div className="first-head">
              <h3>{firstProject.title}</h3>
              <span className="badge">{firstProject.genre}</span>
            </div>
            <p className="first-core">{firstProject.coreGameplay}</p>
            <div className="first-grid">
              <div>
                <h4>Main features</h4>
                <ul>
                  {firstProject.features.map((f) => (
                    <li key={f}>{f}</li>
                  ))}
                </ul>
              </div>
              <div>
                <h4>Target audience</h4>
                <p>{firstProject.audience}</p>
                <h4>Monetization ideas</h4>
                <ul>
                  {firstProject.monetization.map((m) => (
                    <li key={m}>{m}</li>
                  ))}
                </ul>
              </div>
            </div>
          </div>
        </section>

        <section className="section">
          <h2>
            All 15 Work Plans{" "}
            <span className="count">
              {filtered.length}/{gamePlans.length}
            </span>
          </h2>
          <div className="grid">
            {filtered.map((p) => (
              <PlanCard key={p.id} plan={p} />
            ))}
          </div>
        </section>
      </main>

      <footer className="footer">
        Planning only — no execution. Generated by Hermes Agent · {new Date().getFullYear()}
      </footer>
    </div>
  );
}
